apiVersion: v1
kind: Service
metadata:
  name: {{ include "front.fullname" . }}
  labels:
{{ include "front.labels" . | indent 4 }}
spec:
  type: {{ .Values.front.service.type | default .Values.global.service.type }}
  ports:
    - port: {{ .Values.front.service.port | default .Values.global.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "front.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
